name: Deploy front

on:
    push:
        branches:
            - master
    pull_request:
        branches:
            - master

jobs:
    dist_generate:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@master

            - uses: actions/setup-node@master

            - name: install dependecies
              run: npm install

            - name: set vue
              run: npm install @vue/cli

            - name: build
              run: npm run build

    push_to_another:
        needs: dist_generate
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@master

            - name: push to back
              uses: cpina/github-action-push-to-another-repository@master
              env:
                API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
              with:
                source-directory: 'dist'
                destination-github-username: 'JCH97'
                destination-repository-name: 'IS-Back'
                user-email: jc1997hdez@gmail.com