name: Deploy front

on:
    push:
        branches:
            - master
    pull_request:
        branches:
            - master

jobs:
    dist_generate:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@master

            - uses: actions/setup-node@master

            - name: install dependecies
              run: |
                 npm install
                 npm run build

    push_to_another:
        needs: dist_generate
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@master

            - name: push to back
              uses: johno/actions-push-subdirectories@master
              env:
                API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
                GITHUB_TOKEN: ${{ secrets.TOKEN_GITHUB }}
              with:
                args: dist JCH97 IS-Back master